catalog/urls.py
# -*- coding:utf-8 -*-
'''
@Description: 目录应用程序URL包含在项目中，并映射 catalog／，因此访问此映射程序的URL必须从 catalog／开始（在正斜杠之后，映射程序正在工作于所有URL字符串）
@Author: lamborghini1993
@Date: 2019-03-07 20:19:42
@UpdateDate: 2019-03-11 17:20:24
'''

from django.urls import path, include
from catalog import views

urlpatterns = [
    path('', views.index, name='index'),

    # 对于书本详细信息路径，URL 模式使用特殊语法，来捕获我们想要查看的书本的特定 id。
    # 语法非常简单：尖括号定义要捕获的URL部分，包含视图可用于访问捕获数据的变量的名称。
    # 例如，<something> 将捕获标记的模式，并将值作为变量 “something” ，传递给视图。
    # 您可以选择在变量名称前，加上一个定义数据类型的转换器规范（int，str，slug，uuid，path）。
    #
    # 在这里，我们使用 '<int:pk>' 来捕获 book id，它必须是一个整数，并将其作为名为 pk 的参数（主键的缩写）传递给视图。
    # 所有pk的意思是主键，不可改为其他字段
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),

    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),

    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),

]

locallibray/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Use include() to add URLS from the catalog application and authentication system
from django.urls import include
# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
# -*- coding:utf-8 -*-
'''
@Description: 各种模型
@Author: lamborghini1993
@Date: 2019-03-07 20:50:03
@UpdateDate: 2019-03-11 17:32:16
'''

import uuid

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date


class Genre(models.Model):
    """
    类型模型
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Book(models.Model):
    """
    书模型
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
    display_genre.short_description = '类型'


class BookInstance(models.Model):
    """
    BookInstance 模式
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', '保养中'),
        ('o', '已被借阅'),
        ('a', '可借阅'),
        ('r', '已被预定'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    """
    作者模型
    Model representing an author.
    """
    name = models.CharField(max_length=100, null=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name

catalog/views.py
# -*- coding:utf-8 -*-
'''
@Description: 视图是处理HTTP请求的功能，根据需要从数据库获取数据，
    通过使用HTML模板呈现此数据生成HTML页面，然后以HTTP响应返回HTML以显示给用户。
    索引视图遵循此模型 - 它提取有关数据库中有多少Book，
    BookInstance 可用 BookInstance 和 Author 记录的信息，
    并将其传递给模板以进行显示。
@Author: lamborghini1993
@Date: 2019-03-07 20:03:04
@UpdateDate: 2019-03-11 17:36:51
'''

from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin   # 只有登录用户才能调用此视图


def index(request):
    """
    View function for home page of site.
    """
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()    # The 'all()' is implied by default.

    sVisits = "num_visits"
    num_visits = request.session.get(sVisits, 0)
    request.session[sVisits] = num_visits + 1

    return render(
        request,
        'index.html',
        context={
            "num_books": num_books,
            "num_instances": num_instances,
            "num_instances_available": num_instances_available,
            "num_authors": num_authors,
            sVisits: num_visits,
        }
    )


class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'   # your own name for the list as a template variable
    # queryset = Book.objects.filter(title__icontains='war')[:5]  # Get 5 books containing the title war
    # template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location

    # def get_queryset(self):
    #     """
    #     覆盖get_queryset()方法，来更改返回的记录列表。这比仅仅设置queryset属性更灵活
    #     """
    #     # return Book.objects
    #     return Book.objects.filter(title__icontains='三')[:5]

    def get_context_data(self, **kwargs):
        """
        覆盖get_context_data() ，以将其他上下文变量传递给模板（例如，默认情况下传递书本列表）。下面的片段，显示了如何将一个名为“some_data”的变量添加到上下文中（然后它将作为一个模板变量，而被提供）
        """
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author


class AuthorDetailView(generic.DetailView):
    # template_name 默认是 name_mode.html(author_detail.html)
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'books' %}">All books</a></li>
                    <li><a href="{% url 'authors' %}">All authors</a></li>
                    
                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                    {% endif %}
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}
            </div>
        </div>

    </div>
</body>

</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author: {{ author.name }}</h1>

<p><strong>Name:</strong> <a href="">{{ author.name }}</a></p> <!-- author detail link not yet defined -->
<p><strong>date_of_birth:</strong> {{ author.date_of_birth }}</p>
<p><strong>date_of_death:</strong> {{ author.date_of_death }}</p>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author List</h1>

{% if author_list %}
<ul>

    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">{{ author.name }}</a> ({{author.date_of_birth}})
    </li>
    {% endfor %}

</ul>
{% else %}
<p>There are no authors in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %},
    {% endif %}{% endfor %}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Book List</h1>

{% if book_list %}
<ul>

    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
    </li>
    {% endfor %}

</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Borrowed books</h1>

{% if bookinstance_list %}
<ul>

    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
    </li>
    {% endfor %}
</ul>

{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

<p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla
    Developer Network.</p>

<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}